
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "./provider/provider";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";


const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = {
  title: "Employee Management System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 text-gray-800`}>
        <Providers>
          <div className="flex h-screen overflow-hidden">
              <Sidebar />
              <div className="flex flex-col flex-1">
                <Navbar />
                <main className="flex-1 overflow-y-auto p-6">{children}</main>
              </div>
            </div>
        </Providers>
      </body>
    </html>
  );
}
