
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "./provider/provider";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import { getCurrentUser } from "@/libs/getCurrentUser"; // your auth helper

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Employee Management System",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // get the current user (authenticated or not)
  const user = await getCurrentUser();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 text-gray-800`}
      >
        <Providers>
          <div className="flex h-screen overflow-hidden">
            {user && <Sidebar />} {/* only show sidebar if user exists */}
            <div className="flex flex-col flex-1">
              {user && <Navbar />} {/* only show navbar if user exists */}
              <main className="flex-1 overflow-y-auto p-6">{children}</main>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
